"""Archore Qtile config

Do not edit this file directly if you want to configure your system.
Instead, modify config.ini, floating_layouts.ini,
mouse.ini, shortcuts.ini, and workspaces.ini.
"""
import configparser
import os

from libqtile import layout, hook
from libqtile.config import Click, Drag, Match
from libqtile.lazy import lazy

from _floating_layout import floating_layout
from _groups import groups
from _keys import keys
from _layouts import layouts
from _mouse import mouse
from _screens import screens, widget_defaults


path_home = os.path.expanduser('~')
path_config = os.path.join(path_home, ".config/qtile/config.ini")
# For debugging
if not os.path.exists(path_config):
    path_config = "config.ini"
config = configparser.ConfigParser(allow_no_value=True)
config.optionxform = str
config.read(path_config)

auto_full_screen = config["qtile"].getboolean("auto_full_screen")
bring_front_click = config["qtile"].getboolean("bring_front_click")
cursor_warp = config["qtile"].getboolean("cursor_warp")
dgroups_key_binder = None
dgroups_app_rules = []  # type: List
focus_on_window_activation = config["qtile"]["focus_on_window_activation"]
follow_mouse_focus = config["qtile"].getboolean("follow_mouse_focus")
reconfigure_screens = config["qtile"].getboolean("reconfigure_screens")
wmname = config["qtile"]["wmname"]
auto_minimize = config["qtile"].getboolean("auto_minimize")

@hook.subscribe.startup_once
def autostart():
    pass
