"""Mouse config

Do not edit this file directly.
Instead, edit mouse.ini.
"""
import configparser
import os

from libqtile.lazy import lazy
from libqtile.config import Click, Drag

from keys import decipher_shortcut, mod


path_home = os.path.expanduser('~')
path_config = os.path.join(path_home, ".config/qtile/mouse.ini")
# For debugging
if not os.path.exists(path_config):
    path_config = "mouse.ini"
config = configparser.ConfigParser(allow_no_value=True)
config.optionxform = str
config.read(path_config)

mouse = []

# Manipulate floating layouts
shortcut = config["floating_layout"]["set_position_floating"]
modifier, key = decipher_shortcut(shortcut, mod=mod)
mouse.append(
    Drag(modifier, key, lazy.window.set_position_floating(),
         start=lazy.window.get_position())
)

shortcut = config["floating_layout"]["set_size_floating"]
modifier, key = decipher_shortcut(shortcut, mod=mod)
mouse.append(
    Drag(modifier, key, lazy.window.set_size_floating(),
         start=lazy.window.get_size())
)

shortcut = config["floating_layout"]["bring_to_front"]
modifier, key = decipher_shortcut(shortcut, mod=mod)
mouse.append(
    Click(modifier, key, lazy.window.bring_to_front())
)
